### ISSUE TITLE
Only user can see error response 

### ISSUE THREAD

**Issue by Tag365** [TomSchmanke/VoteKick-DiscordBot#2]
Make the Response _You have to be in the same voice channel as the user!_ for the user only.

Reference to the feature:
![image](https://user-images.githubusercontent.com/56080514/155855907-a59c61a8-374f-4a3e-b83f-6bd74bce09b7.png)

**Comment by TomSchmanke** [comment]
Implemented in commit https://github.com/TomSchmanke/VoteKick-DiscordBot/commit/23cce3bc50cff96fbdd7e54f5bee1dc6f0ea5235
